{
    "issue": {
        "title": "Why does DataFusion throw a Tokio 0.2 runtime error?",
        "body": "***Note**: This issue was originally created as [ARROW-11578](https://issues.apache.org/jira/browse/ARROW-11578). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nthread 'tests::simple_join' panicked at 'must be called from the context of a Tokio 0.2.x runtime configured with either `basic_scheduler` or `threaded_scheduler`'.\r\n\r\n```Rust\n\r\n    #[tokio::test]\r\n    async fn simple_join() -> Result<()> {\r\n        let schema1 = Arc::new(Schema::new(vec![\r\n            Field::new(\"a\", DataType::Utf8, false),\r\n            Field::new(\"b\", DataType::Int32, false),\r\n        ]));\r\n        let schema2 = Arc::new(Schema::new(vec![\r\n            Field::new(\"c\", DataType::Utf8, false),\r\n            Field::new(\"d\", DataType::Int32, false),\r\n        ]));\r\n\r\n        // define data.\r\n        let batch1 = RecordBatch::try_new(\r\n            schema1.clone(),\r\n            vec![\r\n                Arc::new(StringArray::from(vec![\"a\", \"b\", \"c\", \"d\"])),\r\n                Arc::new(Int32Array::from(vec![1, 10, 10, 100])),\r\n            ],\r\n        )?;\r\n        // define data.\r\n        let batch2 = RecordBatch::try_new(\r\n            schema2.clone(),\r\n            vec![\r\n                Arc::new(StringArray::from(vec![\"a\", \"b\", \"c\", \"d\"])),\r\n                Arc::new(Int32Array::from(vec![1, 10, 10, 100])),\r\n            ],\r\n        )?;\r\n\r\n        let mut ctx = ExecutionContext::new();\r\n\r\n        let table1 = MemTable::try_new(schema1, vec![vec![batch1]])?;\r\n        let table2 = MemTable::try_new(schema2, vec![vec![batch2]])?;\r\n\r\n        ctx.register_table(\"t1\", Box::new(table1));\r\n        ctx.register_table(\"t2\", Box::new(table2));\r\n\r\n        let sql = concat!(\r\n            \"SELECT a, b, d \",\r\n            \"FROM t1 JOIN t2 ON a = c \",\r\n            \"ORDER BY b ASC \",\r\n            \"LIMIT 3\"\r\n        );\r\n\r\n        let plan = ctx.create_logical_plan(&sql)?;\r\n        let plan = ctx.optimize(&plan)?;\r\n        let plan = ctx.create_physical_plan(&plan)?;\r\n\r\n        let batches = collect(plan).await?;\r\n        let formatted = arrow::util::pretty::pretty_format_batches(&batches).unwrap();\r\n        let actual_lines: Vec<&str> = formatted.trim().lines().collect();\r\n\r\n        let expected = vec![\r\n            \"+---+----+----+\",\r\n            \"| a | b  | d  |\",\r\n            \"+---+----+----+\",\r\n            \"| a | 1  | 1  |\",\r\n            \"| b | 10 | 10 |\",\r\n            \"| c | 10 | 10 |\",\r\n            \"+---+----+----+\",\r\n        ];\r\n\r\n        assert_eq!(expected, actual_lines);\r\n\r\n        Ok(())\r\n    }\r\n```\r\n",
        "created_at": "2021-02-09T22:54:15.000Z",
        "updated_at": "2021-04-26T13:35:22.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Rust - DataFusion",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2021-04-26T13:29:41.000Z"
    },
    "comments": [
        {
            "created_at": "2021-04-26T13:29:39.968Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-11578?focusedCommentId=17332378) by Andrew Lamb (alamb):*\nMigrated to github: https://github.com/apache/arrow-datafusion/issues/176"
        },
        {
            "created_at": "2021-04-26T13:35:22.308Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-11578?focusedCommentId=17332413) by Andrew Lamb (alamb):*\nSorry `[~gangliao]` \u2013 I hadn't seen this ticket before. \r\n\r\nDataFusion now requires tokio 1.x so if you tried to run this program using tokio 0.2 you'll get some sort of strange runtime error "
        }
    ]
}