{
    "issue": {
        "title": "\"ImportError: liborc.so\" with miniconda pyarrow=1.0.1 when \"import pyarrow\"",
        "body": "***Note**: This issue was originally created as [ARROW-10152](https://issues.apache.org/jira/browse/ARROW-10152). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nI cannot run \"`import pyarrow`\" with `pyarrow=1.0.1` in dockerized miniconda. It works fine with `pyarrow=1.0.0` though. The error is:\r\n> File \"<string>\", line 1, in <module>\n> File \"/opt/conda/envs/condaenv/lib/python3.8/site-packages/pyarrow/__init__.py\", line 62, in <module>\n> import pyarrow.lib as _lib\n> ImportError: liborc.so: cannot open shared object file: No such file or directory\r\n----\r\nTo reproduce, use:\r\n\r\nDockerfile:\r\n```java\n\r\nFROM continuumio/miniconda3:latest\r\nCOPY environment.yml .\r\nRUN conda install -n base -c defaults conda=4.*\r\nRUN conda env create -n condaenv  # Installs environment.yml\r\nRUN conda list -n condaenv  # Just for comparison\r\nENV PATH /opt/conda/envs/condaenv/bin:$PATH\r\nRUN python -c \"import pyarrow\"\r\n```\r\nenvironment.yml:\r\n```java\n\r\nname: condaenv\r\nchannels:\r\n  - defaults\r\n  - conda-forge\r\n  - conda-forge/label/rc\r\ndependencies:\r\n  - pyarrow==1.0.1\n```",
        "created_at": "2020-10-01T21:26:20.000Z",
        "updated_at": "2020-10-05T16:09:33.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Python",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2020-10-05T16:03:26.000Z"
    },
    "comments": [
        {
            "created_at": "2020-10-02T18:54:48.899Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-10152?focusedCommentId=17206406) by Uwe Korn (uwe):*\nCan you post the output of `conda list`?"
        },
        {
            "created_at": "2020-10-05T15:54:44.773Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-10152?focusedCommentId=17208151) by Uwe Korn (uwe):*\nNote that the environment.yml is faulty here. If you use conda-forge, you should set it to a higher priority than defaults."
        },
        {
            "created_at": "2020-10-05T16:02:46.125Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-10152?focusedCommentId=17208154) by Pac A. He (apacman):*\nThere is nothing wrong with `environment.yml`. The issue was fixed on Friday by someone by a new release of pyarrow at <https://anaconda.org/conda-forge/pyarrow/files> . It now works.\r\n\r\nThe default `anaconda` channel is on v0.15.1, so there is no conflict."
        }
    ]
}