{
    "issue": {
        "title": "[CI][Python] Have a way to reproduce hypothesis failures from CI",
        "body": "***Note**: This issue was originally created as [ARROW-18127](https://issues.apache.org/jira/browse/ARROW-18127). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nWe have a nightly test build with hypothesis enabled, and those tests fail / crash from time to time, eg https://github.com/ursacomputing/crossbow/actions/runs/3286024804/jobs/5413689973\r\n\r\nIdeally, if there is such a failure, we should actually fix that test case. But that requires us to be able to reproduce the failure locally. \r\nIf it's an actual test failure, hypothesis should print some information to re-run it locally with the same input (https://hypothesis.readthedocs.io/en/latest/reproducing.html#reproducing-an-example-with-reproduce-failure). \r\nBut if it is segfaulting, this information is not printed by default.\r\n\r\nAnother idea might to save the ./hypothesis/examples directory as artifact on the CI build, to use it locally, but probably that might have the same issue of not having the information we need in case of a crash.",
        "created_at": "2022-10-21T12:34:31.000Z",
        "updated_at": "2022-10-21T12:34:31.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Continuous Integration",
            "Component: Python",
            "Type: test"
        ],
        "closed": false
    },
    "comments": []
}