{
    "issue": {
        "title": "[Python] to_pandas conversion removes timezone from type",
        "body": "***Note**: This issue was originally created as [ARROW-6652](https://issues.apache.org/jira/browse/ARROW-6652). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nCalling `to_pandas` on a `pyarrow.Array` with a timezone aware timestamp type, removes the timezone in the resulting `pandas.Series`.\r\n\r\n```Java\n\r\n>>> import pyarrow as pa\r\n>>> a = pa.array([1], type=pa.timestamp('us', tz='America/Los_Angeles'))\r\n>>> a.to_pandas()\r\n0   1970-01-01 00:00:00.000001\r\ndtype: datetime64[ns]\r\n```\r\n\r\nPrevious behavior from 0.14.1 of converting a `pyarrow.Column` `to_pandas` retained the timezone.\r\n```Java\n\r\nIn [4]: import pyarrow as pa \r\n   ...: a = pa.array([1], type=pa.timestamp('us', tz='America/Los_Angeles'))  \r\n   ...: c = pa.Column.from_array('ts', a) \r\n\r\nIn [5]: c.to_pandas()                                                                                                        \r\nOut[5]: \r\n0   1969-12-31 16:00:00.000001-08:00\r\nName: ts, dtype: datetime64[ns, America/Los_Angeles]\r\n```",
        "created_at": "2019-09-21T16:58:02.000Z",
        "updated_at": "2019-09-24T13:43:22.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Python",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2019-09-22T00:28:39.000Z"
    },
    "comments": [
        {
            "created_at": "2019-09-21T17:00:31.402Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-6652?focusedCommentId=16935089) by Bryan Cutler (bryanc):*\n`[~wesm]` or `[~apitrou]` \u00a0 would you be able to take a look at this?"
        },
        {
            "created_at": "2019-09-21T17:03:26.495Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-6652?focusedCommentId=16935092) by Antoine Pitrou (apitrou):*\nAlso cc `[~jorisvandenbossche]`"
        },
        {
            "created_at": "2019-09-21T17:42:39.016Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-6652?focusedCommentId=16935106) by Joris Van den Bossche (jorisvandenbossche):*\nThis should be an easy fix. It seems that the `Column.to_pandas` had a specific check for this case: \r\n\r\nhttps://github.com/apache/arrow/blob/5f564424c71cef12619522cdde59be5f69b31b68/python/pyarrow/table.pxi#L467-L478\r\n\r\nthat we can add back to Array.to_pandas"
        },
        {
            "created_at": "2019-09-21T18:05:16.675Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-6652?focusedCommentId=16935111) by Joris Van den Bossche (jorisvandenbossche):*\nQuickly did a PR (https://github.com/apache/arrow/pull/5462), thanks for the catch `[~bryanc]` !"
        },
        {
            "created_at": "2019-09-22T00:28:39.828Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-6652?focusedCommentId=16935170) by Wes McKinney (wesm):*\nIssue resolved by pull request 5462\n<https://github.com/apache/arrow/pull/5462>"
        }
    ]
}