{
    "issue": {
        "title": "[C++][Python] Compressed Feather file written with pyarrow 0.17 not readable in pyarrow 2.0.0+",
        "body": "***Note**: This issue was originally created as [ARROW-11163](https://issues.apache.org/jira/browse/ARROW-11163). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nOriginally from https://stackoverflow.com/questions/65413407/reading-in-feather-file-in-pyarrow-error-arrowinvalid-unrecognized-compressio\r\n\r\n\r\nWriting with pyarrow 0.17:\r\n\r\n```python\n\r\nIn [1]: pa.__version__\r\nOut[1]: '0.17.0'\r\n\r\nIn [2]: table = pa.table({'a': range(100)})\r\n\r\nIn [3]: from pyarrow import feather\r\n\r\nIn [4]: feather.write_feather(table, \"test_pa017_explicit.feather\", compression=\"lz4\", version=2)\r\n\r\n# according to docstring, this should do the same, but apparently not\r\nIn [5]: feather.write_feather(table, \"test_pa017_default.feather\")\r\n```\r\n\r\nReading with pyarrow 1.0.0 works for both files, but reading it with master (pyarrow 2.0.0 gives the same error):\r\n\r\n```python\n\r\nIn [121]: pa.__version__\r\nOut[121]: '3.0.0.dev552+g634f993f4'\r\n\r\nIn [123]: feather.read_table(\"test_pa017_default.feather\")\r\nOut[123]:\r\npyarrow.Table\r\na: int64\r\n\r\nIn [124]: feather.read_table(\"test_pa017_explicit.feather\")\r\n---------------------------------------------------------------------------\r\nArrowInvalid                              Traceback (most recent call last)\r\n<ipython-input-124-700e4b059ed5> in <module>\r\n----> 1 feather.read_table(\"test_py017_explicit.feather\")\r\n\r\n~/scipy/repos/arrow/python/pyarrow/feather.py in read_table(source, columns, memory_map)\r\n    238\r\n    239     if columns is None:\r\n--> 240         return reader.read()\r\n    241\r\n    242     column_types = [type(column) for column in columns]\r\n\r\n~/scipy/repos/arrow/python/pyarrow/feather.pxi in pyarrow.lib.FeatherReader.read()\r\n\r\n~/scipy/repos/arrow/python/pyarrow/error.pxi in pyarrow.lib.check_status()\r\n\r\nArrowInvalid: Unrecognized compression type: LZ4\r\nIn ../src/arrow/ipc/reader.cc, line 538, code: (_error_or_value8).status()\r\nIn ../src/arrow/ipc/reader.cc, line 594, code: GetCompressionExperimental(message, &compression)\r\nIn ../src/arrow/ipc/reader.cc, line 942, code: (_error_or_value23).status()\r\n```",
        "created_at": "2021-01-07T14:57:24.000Z",
        "updated_at": "2021-01-11T15:48:19.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: C++",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2021-01-11T15:48:11.000Z"
    },
    "comments": [
        {
            "created_at": "2021-01-11T15:48:11.877Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-11163?focusedCommentId=17262739) by Antoine Pitrou (apitrou):*\nIssue resolved by pull request 9128\n<https://github.com/apache/arrow/pull/9128>"
        }
    ]
}